name: "The Podcast Generator"
author: "Marco Rosa"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "green"
inputs:
  email:
    description: "The commiter's email address"
    required: true
    default: ${{ github.action }}@localhost
  name:
    description: "The commier's name"
    required: true
    default: ${{ github.actor }}
